---
kind: pipeline
type: docker
name: docker-build

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    tags: 
     - latest
     - ${DRONE_TAG}
    dockerfile: Dockerfile
    repo: unknowndev7690/web
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
trigger:
  event:
   - tag
node:
  server: "true"
---
kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: pull latest
  commands:
    - cd /storage/server-config && docker-compose pull web && docker-compose up -d
  when:
    event:
      - tag
trigger:
  event:
   - tag      
depends_on:
  - docker-build
node:
  server: "true"
