---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker build . --file Dockerfile --tag web:latest
  when:
    ref:
      include:
       - refs/tags/**
