version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:6-alpine
    command: --appendonly yes
    ports:
      - 6379:6379
    networks:
      - app-net
    volumes:
      - redis:/data

networks:
  app-net:

volumes:
  redis: