name: Master Build and Docker Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
  push:
    name: Docker Build and Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: unknowndev7690/web
          tags: latest
          tag_with_sha: true # optional
          cache_froms: unknowndev7690/web:latest # optional
          add_git_labels: true # optional
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: cd /storage/server-config && docker-compose pull web && docker-compose up -d web
          host: ${{ secrets.HOST }}
          username: dockeruser
          privateKey: ${{ secrets.SSH_KEY}}
