name: Docker Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build image
        run: docker build . --file Dockerfile


