name: Docker Push
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    name: Docker Push
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
         username: ${{ secrets.DOCKER_USERNAME }} # optional
         password: ${{ secrets.DOCKER_PASSWORD }} # optional
         repository: unknowndev7690/web
         tags: latest
         tag_with_ref: true # optional
         cache_froms: unknowndev7690/web:latest # optional
         add_git_labels: true # optional
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: cd /storage/server-config && docker-compose pull web && docker-compose up -d web
          host: ${{ secrets.HOST }}
          username: dockeruser
          privateKey: ${{ secrets.SSH_KEY}}
