name: Build, Test, and Lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - master
    - dev
    paths-ignore:
      - 'README.md'
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin "$GITHUB_HEAD_REF"
      if: github.event_name == 'pull_request'
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: golangci/golangci-lint-action@v2
      name: Run golangci-lint
      with:
        version: v1.39.0
      continue-on-error: true
    - name: Run Unit tests
      run: |
        make test  
    - uses: shogo82148/actions-goveralls@v1.2.0
      with:
        path-to-profile: profile.cov
  push:
    name: Docker Build and Push
    timeout-minutes: 5
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin "$GITHUB_HEAD_REF"
        if: github.event_name == 'pull_request'
      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: unknowndev7690/web
          tags: latest
          tag_with_sha: true # optional
          cache_froms: unknowndev7690/web:latest # optional
          add_git_labels: true # optional
          push: ${{ startsWith(github.ref, 'refs/heads/master') && github.repository_owner == 'Rich7690' }}