name: Quality
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - master
    - dev
    paths-ignore:
      - 'README.md'
jobs:
  lint:
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin "$GITHUB_HEAD_REF"
      if: github.event_name == 'pull_request'
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Run Unit tests
      run: |
        make test  
    - uses: shogo82148/actions-goveralls@v1.2.0
      with:
        path-to-profile: profile.cov
