name: Quality
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - master
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin "$GITHUB_HEAD_REF"
      if: github.event_name == 'pull_request'
    - uses: shogo82148/actions-goveralls@v1.2.0
      with:
        path-to-profile: profile.cov
